sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "20020725"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    #为了向github推送需要删除如下两个字段
    access-key-id:
    access-key-secret:
    bucket-name: web-tlias-demo17gzm

  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid: wx3412be4ff2e4a7d2
    secret: 365a15aa5da2d410b10c2a031211ef87


